# [作業目標]


1. 請接下列資料依照指定規則做合併：

```
- 依照 fruit 欄位做合併
- 依照 index 索引做合併
```

2. [簡答題] 承上題，請問為什麼依照 merge 合併後有些資料不見了？

3. [簡答題] 承上題，請問為什麼依照 index 合併會發生錯誤？請用程式解決。

# 作業

In [18]:
# 記得先 Import 正確的套件

import numpy as np
import pandas as pd

### 1. 請接下列資料依照指定規則做合併：

```
- 依照 fruit 欄位做合併
- 依照 index 索引做合併
```

In [19]:
df1 = pd.DataFrame({
    'fruit': ['apple', 'banana', 'orange'] * 3,
    'weight': ['high', 'medium', 'low'] * 3,
    'price': np.random.randint(0, 15, 9)
})

df2 = pd.DataFrame({
    'fruit': ['apple', 'orange', 'pine'] * 2,
    'weight': ['high', 'low'] * 3,
    'price': np.random.randint(0, 15, 6)
})
print(df1)
print(df2)

    fruit  weight  price
0   apple    high     14
1  banana  medium      1
2  orange     low     14
3   apple    high      5
4  banana  medium      6
5  orange     low      3
6   apple    high      3
7  banana  medium      6
8  orange     low      0
    fruit weight  price
0   apple   high      3
1  orange    low      6
2    pine   high      0
3   apple    low      2
4  orange   high      4
5    pine    low      0

In [20]:
# - 依照 fruit 欄位做合併

'''
Your Code
'''
pd.merge(df1, df2, on='fruit')

     fruit weight_x  price_x weight_y  price_y
0    apple     high       14     high        3
1    apple     high       14      low        2
2    apple     high        5     high        3
3    apple     high        5      low        2
4    apple     high        3     high        3
5    apple     high        3      low        2
6   orange      low       14      low        6
7   orange      low       14     high        4
8   orange      low        3      low        6
9   orange      low        3     high        4
10  orange      low        0      low        6
11  orange      low        0     high        4

In [21]:
# - 依照 index 索引做合併

'''
Your Code
'''
pd.merge(df1, df2)

   fruit weight  price
0  apple   high      3

### 2. [簡答題] 承上題，請問為什麼依照 merge 合併後有些資料不見了？

In [22]:
'''
Your Code

因為 medium 只存在一邊。
'''

'\nYour Code\n\n因為 medium 只存在一邊。\n'

### 3. [簡答題] 承上題，請問為什麼依照 index 合併會發生錯誤？請用程式解決。

In [23]:
'''
Your Code
'''
pd.merge(df1, df2, left_index=True, right_index=True)

  fruit_x weight_x  price_x fruit_y weight_y  price_y
0   apple     high       14   apple     high        3
1  banana   medium        1  orange      low        6
2  orange      low       14    pine     high        0
3   apple     high        5   apple      low        2
4  banana   medium        6  orange     high        4
5  orange      low        3    pine      low        0